# Use postgres/example user/password credentials

services:

  postgres:
    image: postgres
    restart: always
    ports:
      - ${PORT_POSTGRES}:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      DATABASE_HOST: ${DATABASE_HOST}
    
  pgadmin:
      image: dpage/pgadmin4:snapshot
      environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      ports:
        - ${PORT_PGADMIN}:80
      depends_on:
        - postgres
